### PR TITLE
Fix phrasing

### PR DESCRIPTION
**Pull request by kurtmckee**
Also, break the changed line at sentence boundaries to reduce diff noise in future changes.

### CODE REVIEW

**Comment by kurtmckee** [comment]
@itamarhaber It looks like many people are submitting PR's to fix the same typos. Would you review the current batch of PR's? If that makes my changes redundant then I can rebase or close my PR's. Thanks!

**Comment by kurtmckee** [comment]
@yangbodong22011, @ShooterIT, @enjoy-binbin, @madolson, @hwware, pinging you here as you are listed as "the people" for the redis org on GitHub.

The `try.redis` site was extremely helpful as I started learning Redis so I'm hopeful to contribute back to it. I see that there are a number of PR's to fix typos and phrasing for this repo. If you're able, would you review those PR's? I can then close my own PR's if they're redundant, or update them as needed.

Thanks for your work on Redis!

**Comment by enjoy-binbin** [comment]
thanks for the fix. it look good. I usually don't notice this..
I think you can summarize these fix (or not)
i will post this to ours slack chatroom, and see if anyone else can help (i am not really good at english)

**Comment by kurtmckee** [comment]
Thank you, @enjoy-binbin! Hopefully someone can help review the PR's in this repository soon. :smile: :+1:

**Comment by enjoy-binbin** [comment]
i heard that:
    we want to take down this website, fixing it is too much effort and considering that, fixing typos is a wasted effort.

other members want to focus on more important things, consider the `take down`, sorry, we won't be able to review it now
anyway, thanks for the PRs

**Comment by kurtmckee** [comment]
No problem. Thank you for the quick response, and have a great day!

**Pull request closed without merging**
